### ISSUE TITLE
Scan QR Screen

### ISSUE THREAD

**Issue by gHashTag** [DAO-999-NFT/faraway-kingdom#22]
> Ну тут взади еще будет вид с камеры
#### [Figma link](https://www.figma.com/file/HJ4PXwywZfP213klET5Bx6/%D0%A2%D1%80%D0%B8%D0%B4%D0%B5%D0%B2%D1%8F%D1%82%D0%BE%D0%B5-%D0%A6%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%BE?node-id=386%3A1385&t=Ymbfnh0Dn8W2bklu-1)
<img width="244" alt="Снимок экрана 2023-02-16 в 20 44 20" src="https://user-images.githubusercontent.com/6774813/219415742-19d381d2-e85f-496b-905d-94f8bfe0cde3.png">

**Comment by Crazy-MIXER** [comment]
16 hours
- add all QRScan components
- add dependence QRScanner with TicketDetails
