### ISSUE TITLE
Search screen

### ISSUE THREAD

**Issue by gHashTag** [DAO-999-NFT/faraway-kingdom#24]
> Можно использовать [код из haqq](https://github.com/haqq-network/haqq-wallet/tree/main/src/components/ui/custom-header)
#### [Figma link](https://www.figma.com/file/HJ4PXwywZfP213klET5Bx6/%D0%A2%D1%80%D0%B8%D0%B4%D0%B5%D0%B2%D1%8F%D1%82%D0%BE%D0%B5-%D0%A6%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%BE?node-id=386%3A1120&t=Ymbfnh0Dn8W2bklu-1)

<img width="613" alt="Снимок экрана 2023-02-16 в 20 48 36" src="https://user-images.githubusercontent.com/6774813/219416981-8d60b525-831d-4d7b-a69a-44b8c196b249.png">

**Comment by Crazy-MIXER** [comment]
- add SearchScreen
- add SearchBar
- add SearchNoResults
- refactor TicketCardRow

**Comment by Crazy-MIXER** [comment]
4.5 hours
