### ISSUE TITLE
Change tabs

### ISSUE THREAD

**Issue by gHashTag** [DAO-999-NFT/faraway-kingdom#33]
Переделать флоу скринов приложения билетов так, чтобы можно было вернуться на главный скрин и с него попасть куда угодно
Изменить табы на:
Tickets - Вадим
Staking - MONK
Governance - МОНК

**Comment by Crazy-MIXER** [comment]
Governance: 7 hours

**Comment by Crazy-MIXER** [comment]
- add Staking components
  Staking: 3.5 hours
