### ISSUE TITLE
Экран создания билета

### ISSUE THREAD

**Issue by gHashTag** [DAO-999-NFT/faraway-kingdom#49]
Пока нету контракта необходимо прописать поля которые точно будут

EventName
Start date
End date число (мс)
location {lattitude longitude}
LocationName
Country

**Comment by gHashTag** [comment]
Read https://blog.logrocket.com/best-date-pickers-react-native-app/ (if all OK - use it)

**Comment by Crazy-MIXER** [comment]
7 hours
